<a href="https://colab.research.google.com/github/Felviana/Python_DataScience/blob/main/corrida_de_kart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [17]:
# Nomes dos corredores
nomes_corredores = ["Felipe", "Tha", "Fran", "Vick", "Maria", "Joao"]

In [19]:
#tempo de voltas de corredores

felipe=np.array([50,45,55,46,66,43,54,56,60,59])
tha=np.array([52,45,44,60,50,44,56,67,59, 58])
fran=np.array([49, 48, 47, 50, 52, 53, 55,60,59,58])
vick=np.array([50,51,52,54,55,57,59,60,58,55])
maria=np.array([51,52,53,54,55,54,53,52,51,49])
joao=np.array([51,52,57,54,55,54,53,52,50,49])


In [20]:
# Matriz de tempos de voltas
tempos_voltas = np.array([felipe, tha, fran, vick, maria, joao])
print(tempos_voltas)

[[50 45 55 46 66 43 54 56 60 59]
 [52 45 44 60 50 44 56 67 59 58]
 [49 48 47 50 52 53 55 60 59 58]
 [50 51 52 54 55 57 59 60 58 55]
 [51 52 53 54 55 54 53 52 51 49]
 [51 52 57 54 55 54 53 52 50 49]]


In [21]:
# Calculando a média das voltas para cada corredor
media_voltas = np.mean(tempos_voltas, axis=1)

In [22]:
# Encontrando a volta com a média mais rápida
volta_media_rapida = np.argmin(media_voltas) + 1
print(f"A volta com a média mais rápida foi a volta {volta_media_rapida} com tempo médio de {media_voltas[volta_media_rapida - 1]} segundos.")

A volta com a média mais rápida foi a volta 5 com tempo médio de 52.4 segundos.


In [23]:
# Função para encontrar a melhor volta da prova e em qual volta
def melhor_volta(corredores):
    melhor_tempo = np.min(corredores)
    corredor, volta = np.where(corredores == melhor_tempo)
    return corredor[0], volta[0] + 1  # Adicionamos 1 para compensar o índice base 0
# Encontrando a melhor volta da prova
corredor, volta = melhor_volta(tempos_voltas)
print(f"A melhor volta da prova foi de {nomes_corredores[corredor]} na volta {volta} com {tempos_voltas[corredor, volta - 1]} segundos.")

A melhor volta da prova foi de Felipe na volta 6 com 43 segundos.


In [28]:
# Imprimindo a classificação final em ordem crescente
classificacao=classificacao_final(tempos_voltas)
print("Classificação final em ordem crescente:")
for posicao, corredor_idx in enumerate(classificacao):
     print(f"{posicao + 1}. {nomes_corredores[corredor_idx]} - A melhor média foi {media_voltas[corredor_idx]} segundos.")


Classificação final em ordem crescente:
1. Maria - A melhor média foi 52.4 segundos.
2. Joao - A melhor média foi 52.7 segundos.
3. Fran - A melhor média foi 53.1 segundos.
4. Felipe - A melhor média foi 53.4 segundos.
5. Tha - A melhor média foi 53.5 segundos.
6. Vick - A melhor média foi 55.1 segundos.
