In [27]:
# Numpy

'''
Lista, Matriz e Array

Lista (list)

-Estrutura nativa do Python.
-Aceita tipos variados (números, textos, outras listas).
-Usada para dados genéricos.

Matriz (lista de listas)

-Lista dentro de lista (ex: [[1, 2], [3, 4]]).
-Representa linhas e colunas, mas não é otimizada para cálculo.

Array (numpy.array)

-Vem da biblioteca NumPy.
-Todos os dados são do mesmo tipo (geralmente numéricos).
-Ideal para cálculos rápidos, estatística e ciência de dados.
'''

'\nLista, Matriz e Array\n\nLista (list)\n\n-Estrutura nativa do Python.\n-Aceita tipos variados (números, textos, outras listas).\n-Usada para dados genéricos.\n\nMatriz (lista de listas)\n\n-Lista dentro de lista (ex: [[1, 2], [3, 4]]).\n-Representa linhas e colunas, mas não é otimizada para cálculo.\n\nArray (numpy.array)\n\n-Vem da biblioteca NumPy.\n-Todos os dados são do mesmo tipo (geralmente numéricos).\n-Ideal para cálculos rápidos, estatística e ciência de dados.\n'

In [28]:
import numpy as np
import statistics as st

In [29]:
# Gerando um Array de numeros aleatórios (numeros entre 0 e 1)
dados = np.random.rand(4, 3)
dados

array([[0.38074365, 0.17440614, 0.85369088],
       [0.84153298, 0.24632449, 0.25473251],
       [0.28573519, 0.42958125, 0.29907096],
       [0.3430118 , 0.71423529, 0.20008573]])

In [30]:
dados.dtype # Mostrando o tipo dos dados

dtype('float64')

In [31]:
dados.shape # Mostra o formato (dimensões) de um array.

(4, 3)

In [32]:
dados.ndim # Mostra o número de dimensões (ou seja, quantas "camadas").

2

In [33]:
lista = [1,2,3,4,5,6,7,8,9,10]
dados2 = np.array(lista)
dados2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
lista = [1,2,3,4,5], [6,7,8,9,10]
dados2 = np.array(lista)
dados2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Você recebeu os dados de temperatura média (em °C) de uma cidade durante os 7 dias da semana. Com base nesses dados, responda:

```
temperaturas = np.array ([22.5, 24.0, 19.8, 21.4, 23.0, 25.1, 20.7])
dias = np.array (["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"])
```



In [35]:
'''Qual foi a temperatura média da semana?'''

temperaturas = np.array ([22.5, 24.0, 19.8, 21.4, 23.0, 25.1, 20.7])
dias = np.array (["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"])

media = st.mean(temperaturas)
print(f"Média de temperatura:", round(media, 2),)

Média de temperatura: 22.36


In [36]:
'''Qual foi a temperatura máxima e em que dia ocorreu?'''

temp_max = np.max(temperaturas) # Encontra a maior temperatura
index_max = np.argmax(temperaturas) # Encontra o índice dessa temperatura
dia_max = dias[index_max] # Usa o índice para achar o dia


print(f"A temperatura máxima foi {temp_max}°C e ocorreu no {dia_max}.")

A temperatura máxima foi 25.1°C e ocorreu no Sáb.


In [37]:
'''Quais dias tiveram temperatura acima da média?'''

dias_acima_media = dias[temperaturas > media]
print(dias_acima_media)

['Seg' 'Ter' 'Sex' 'Sáb']


In [38]:
'''Crie um novo array com as temperaturas convertidas para Fahrenheit.
Fórmula: F = C * 1.8 + 32'''

temp_f = (temperaturas * 1.8 + 32)
print(temp_f)

[72.5  75.2  67.64 70.52 73.4  77.18 69.26]


In [39]:
'''Substitua a temperatura de domingo para 22.0°C e recalcule a média.'''

temperaturas2 = np.array ([22.5, 24.0, 19.8, 21.4, 23.0, 25.1, 20.0])
media2 = st.mean(temperaturas2)
print(f"Nova média de temperatura:", round(media2, 2),)

Nova média de temperatura: 22.26
